# Generated by Django 2.2 on 2019-09-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_event_host'),
        ('eventFinderApp', '0002_auto_20190923_2136'),
    ]

    operations = [
    ]
